config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new' #access using /signup
  get 'login'   => 'sessions#new'
  post 'login'  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users, :only => [:create, :new, :edit, :update]
  get 'main'    => 'bugs#index'
  
  resources :bugs
  
  match 'bugs/:id/close' => 'bugs#close', via: [:get, :patch, :put], as: :bug_close

end

app/models/bug.rb
class Bug < ActiveRecord::Base
     validates :name, presence: true, length: {maximum: 50 }
     validates :description, presence: true, length: {maximum: 200 }
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  
  def show
    @bug = Bug.find(params[:id])
  end
  
  def index 
    @bugs = Bug.all
    
    @logs = Log.all 
  end
  
  
  def new
   @bug = Bug.new
  end
  
  def create #taken from the POST form method of new.html
    @bug = Bug.new(bug_params) 
    if @bug.save #handle a successful save
    
    #add log entry for 'create' and save 
    @log_entry = Log.new
    
    time1 = Time.new.to_s
    @log_entry.a_log = time1 + "| " + current_user.name + " created Bug ID: " + @bug.id.to_s 
    @log_entry.save
    
   @bug.update_attribute(:done, false)
  
    redirect_to @bug
    else
      render 'new'
    end
  end
  
  def edit
    @bug = Bug.find(params[:id])
     
  end  
    
  def update
    @bug = Bug.find(params[:id])
    
    #Store 'past state' bug information here 
    @past_bug = @bug.dup
    changed_states = ""
    
    if @bug.update_attributes(bug_params)
      # Handle a successful update.
    
      if @bug.name != @past_bug.name
      changed_states += "NAME: [" + @past_bug.name + " -> " + @bug.name + "] "
      end
      if @bug.description != @past_bug.description
      changed_states += " [updated description] "
      end
      if @bug.precedense != @past_bug.precedense
      changed_states += "PRECEDENSE: [" + @past_bug.precedense + " -> " + @bug.precedense + "] "
      end
          
    #add log entry for 'update' and save 
    @log_entry = Log.new
    time1 = Time.new.to_s
    @log_entry.a_log = time1 + "| " + current_user.name + " updated Bug ID: " + @bug.id.to_s + " CHANGED: " + changed_states
    @log_entry.save
      
      
      redirect_to @bug
    else
      render 'edit'
    end
  end
  
  def destroy
    @bug = Bug.find(params[:id])
  
    @log_entry = Log.new
    time1 = Time.new.to_s
    @log_entry.a_log = time1 + "| " + current_user.name + " deleted Bug ID: " + @bug.id.to_s 
    @log_entry.save
  
    
    @bug.destroy
    flash[:success] = "Bug deleted"
    
    
    redirect_to bugs_url
  end
    
  def close
  
    @bug = Bug.find(params[:id])
    @bug.done = true
    @bug.save
    
    redirect_to bugs_url
  end
  
  
  
    private
  
   def bug_params
    params.require(:bug).permit(:name,:precedense,:description, :done)
   end
  
end

app/views/bugs/close.html.erb
Will this even show?

app/views/bugs/edit.html.erb
<br>
<br> <!-- icant css -->
<br>

<h1>Update the Bug</h1>


<div class="row">
  <div class="col-md-6 col-md-offset-3">
       <%= form_for(@bug) do |f| %> <!-- form_for helper method takes a Active Record Object (user which is initialized but null attributes) and constructs a form to fill it-->
      
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
       
      <%= f.label :description %>
      <%= f.text_field :description, class: 'form-control' %>
        
      <%= f.label :precedense %>
      <select name="bug[precedense]">
  <option value="">Please select</option>
  <option value="Low" selected="selected">Low</option>
  <option value="Medium">Medium</option>
  <option value="High">High</option>
</select>
     
      
      
      <%= f.submit "Save changes", class: "btn btn-primary" %>
    
       
       <% end %>
  </div>
</div>

app/views/bugs/index.html.erb
<br>
<br>
<br>


<% #@bugs = @bugs.precedense.order("id DESC").all %>

<div class = "list_of_bugs">

<table class = "table table-striped">

<thead>
    <tr>
     <th>ID</th>
     <th>PRIORITY</th>    
     <th>NAME</th>   
     <th>CREATED</th> 
     <th>UPDATED</th>
     <th>RESOLVED</th>
     <th>OPTIONS</th>
    </tr>
</thead> 

 <tbody>
    
    
    <% @bugs.each do |i| %>
    <tr>
     <td><%= i.id %></td>
     <td><%= i.precedense %></td>
     <td><%= i.name %></td>
     <td><%= i.created_at %></td> 
     <td><%= i.updated_at %></td>
     <td><%= i.done %></td>
     <td>
      <div class="btn-group" role="group" aria-label="...">
       <button type="button" class="btn btn-default"><%= link_to "Edit", edit_bug_path(i) %></button>
       <button type="button" class="btn btn-default"><%= link_to "Close", bug_close_path(:id => i.id) %></button> <!-- bug_close_path(:id => i.id) -->
       <button type="button" class="btn btn-default"> <%= link_to "Delete", i, method: :delete, data: { confirm: "You sure?" } %></button>
       <button type="button" class="btn btn-default" ><%= link_to "View", bug_path(i)%> </button>
      </div>
     </td>
    </tr
    <% end %>
    
 </tbody>
    
</table>

<button type="button" class="btn btn-success"> <%= link_to "New Bug", new_bug_path %> </button>


<br>
<br> <!-- please learn css -->
<br>

<div class="form-group">
  <label for="comment">Log:</label>
  <textarea class="form-control" rows="10" id="comment" disabled>
   
     <% @logs.each do |i| %>
     <%= i.a_log %>
     <% end %>
  </textarea>
</div>


</div>

app/views/bugs/new.html.erb
<br>
<br> <!-- icant css -->
<br>

<h1>Bugs#new</h1>


<div class="row">
  <div class="col-md-6 col-md-offset-3">
       <%= form_for(@bug) do |f| %> <!-- form_for helper method takes a Active Record Object (user which is initialized but null attributes) and constructs a form to fill it-->
      <% if @bug.errors.any? %>
    <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@bug.errors.count, "error") %>.
    </div>
    <ul>
    <% @bug.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
       
      <%= f.label :description %>
      <%= f.text_field :description, class: 'form-control' %>
        
      <%= f.label :precedense %>
 
<select name="bug[precedense]">
  <option value="">Please select</option>
  <option value="Low" selected="selected">Low</option>
  <option value="Medium">Medium</option>
  <option value="High">High</option>
</select>
     
      
      <%= f.submit "Submit a new Bug", class: "btn btn-primary" %>  <!--<form action="/bugs" class="new_bug" id="new_bug" method="post"> -->
    
       
       <% end %>
  </div>
</div>

app/views/bugs/show.html.erb
<br>
<br>
<br>

<h1><%= @bug.name %></h1>


<h3>Precedense: <%= @bug.precedense %></h3>
<h3>Created At: <%= @bug.created_at %></h3>
<h3>Updated At: <%= @bug.updated_at %></h3>

<div class="form-group">
  <label for="comment">Description:</label>
  <textarea class="form-control" rows="10" id="comment" disabled>
    <%= @bug.description %>
  </textarea>
</div>